
title: Mohamed I Tounsi Resume
url: 'https://tounsils.github.io/'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Mohamed Tounsi  ## put your name
title: 'Full Stack Developer'  ## your title
location: World Wide Remote


## Social Profiles
twitter: #  ## your twitter account url
linkedin: https://www.linkedin.com/in/mohamed-tounsi-20131085/  ## your linkedin account url
dribbble: #  ## you dribbble account url
foursquare: #  ## your foursquare account url
github: https://github.com/tounsils
stackoverflow: https://stackoverflow.com/cv/tounsils

# Update all the sections by editing the files inside _includes folder.
